# Generated by Django 6.0 on 2025-12-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_airport_latitude_airport_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='max_ramp_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_ramp_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_alternate_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_alternate_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_landed_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_landed_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='mldgw_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='mldgw_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='short_name',
            field=models.CharField(max_length=32),
        ),
    ]
