# Generated by Django 6.0 on 2025-12-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aircraft_max_ramp_kg_aircraft_max_ramp_lbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='acmi_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
