# Generated by Django 6.0 on 2025-12-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_aircraft_acmi_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='acmi_cost',
        ),
    ]
