# Generated by Django 6.0 on 2025-12-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_aircraft_acmi_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('main_base', models.CharField(max_length=100)),
                ('block_hour_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aircraft', models.ManyToManyField(related_name='charter_providers', to='main.aircraft')),
            ],
        ),
    ]
