# Generated by Django 6.0 on 2025-12-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_charterprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('currency', models.CharField(max_length=64)),
                ('currency_code', models.CharField(max_length=8)),
                ('region', models.CharField(max_length=64)),
            ],
        ),
    ]
