# Generated by Django 6.0 on 2025-12-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterprovider',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
