# Generated by Django 6.0 on 2025-12-26 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_charterprovider_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterprovider',
            name='main_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charter_providers', to='main.airport'),
        ),
    ]
