# Generated by Django 6.0 on 2025-12-26 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_charterprovider_main_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charterprovider',
            name='aircraft',
        ),
        migrations.AddField(
            model_name='charterprovider',
            name='aircraft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charter_providers', to='main.aircraft'),
            preserve_default=False,
        ),
    ]
