# Generated by Django 6.0 on 2025-12-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_charterprovider_aircraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterprovider',
            name='type',
            field=models.CharField(choices=[('charter', 'Charter'), ('acmi', 'ACMI'), ('by_kg', 'By Kg.')], default='charter', max_length=16),
        ),
    ]
