# Generated by Django 6.0 on 2025-12-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_charterprovider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(max_length=16)),
                ('distance', models.FloatField(help_text='Distance in nautical miles')),
                ('flight_time', models.FloatField(help_text='Flight time in hours')),
                ('adjusted_flight_time', models.FloatField(help_text='Adjusted flight time in hours')),
                ('max_payload', models.FloatField(help_text='Max payload in lbs')),
                ('service_type', models.CharField(max_length=16)),
                ('block_hours_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('route_fuel_gls', models.FloatField(help_text='Route fuel in gallons')),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overflight_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('airport_fees_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aircraft')),
            ],
        ),
    ]
