# Generated by Django 6.0 on 2025-12-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='overflight_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='route',
            name='total_flight_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
