# Generated by Django 6.0 on 2025-12-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_route_overflight_fee_route_total_flight_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.charterprovider'),
            preserve_default=False,
        ),
    ]
