# Generated by Django 6.0 on 2025-12-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_route_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='max_range_at_max_payload',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Range at Max Payload (nm)'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_range_with_max_fuel',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Range with Max Fuel (nm)'),
        ),
    ]
