# Generated by Django 6.0 on 2025-12-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_branchinfo_marketing_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='cargo_positions_lower_deck',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='cargo_positions_main_deck',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='cruise_speed',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_burn_gal',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_burn_lbs',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_range_at_max_payload',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_range_with_max_fuel',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='min_fuel_alternate_gal',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='min_fuel_alternate_lbs',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='min_fuel_landed_gal',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='min_fuel_landed_lbs',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Produce', 'Produce'), ('Meats', 'Meats'), ('Other Perishable', 'Other Perishable'), ('Dry Goods', 'Dry Goods'), ('Technology', 'Technology'), ('Other', 'Other')], max_length=32)),
                ('product_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('trade_unit', models.CharField(choices=[('UN', 'Unit (Un)'), ('BU', 'Bunch (BU)'), ('KG', 'Kilogram (Kg.)'), ('LBS', 'Pound (Lbs.)')], max_length=8)),
                ('fca_cost_per_wu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('packaging', models.CharField(max_length=64)),
                ('packaging_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_per_pack', models.PositiveIntegerField()),
                ('other_info', models.TextField(blank=True, null=True)),
                ('fuel_burn_gal', models.FloatField()),
                ('fuel_burn_lbs', models.FloatField()),
                ('min_fuel_landed_gal', models.FloatField(blank=True, null=True)),
                ('min_fuel_landed_lbs', models.FloatField(blank=True, null=True)),
                ('min_fuel_alternate_gal', models.FloatField(blank=True, null=True)),
                ('min_fuel_alternate_lbs', models.FloatField(blank=True, null=True)),
                ('cargo_positions_main_deck', models.IntegerField()),
                ('cargo_positions_lower_deck', models.IntegerField()),
                ('cruise_speed', models.FloatField()),
                ('max_range_at_max_payload', models.FloatField(blank=True, null=True, verbose_name='Max Range at Max Payload (nm)')),
                ('max_range_with_max_fuel', models.FloatField(blank=True, null=True, verbose_name='Max Range with Max Fuel (nm)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
