# Generated by Django 6.0 on 2025-12-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_aircraft_cargo_positions_lower_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='cargo_positions_lower_deck',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='cargo_positions_main_deck',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='cruise_speed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuel_burn_gal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuel_burn_lbs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_range_at_max_payload',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Range at Max Payload (nm)'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_range_with_max_fuel',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Range with Max Fuel (nm)'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_alternate_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_alternate_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_landed_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='min_fuel_landed_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
