# Generated by Django 6.0 on 2026-01-02 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_aircraft_cargo_positions_lower_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=32, unique=True)),
                ('product_type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('trade_unit', models.CharField(max_length=8)),
                ('fca_cost_per_wu', models.DecimalField(decimal_places=2, max_digits=14)),
                ('packaging', models.CharField(max_length=64)),
                ('packaging_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_per_pack', models.IntegerField()),
                ('packaging_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
