# Generated by Django 6.0 on 2026-01-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('supplier_name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('assigned_branch', models.CharField(max_length=128)),
                ('crop_area', models.CharField(max_length=64)),
                ('crop_yield', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
