# Generated by Django 6.0 on 2026-01-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery',
            field=models.CharField(choices=[('Year-round', 'Year-round'), ('Seasonal', 'Seasonal'), ('On Order', 'On Order'), ('On Shelf', 'On Shelf')], default='Year-round', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ready_for_shelf_days',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
