# Generated by Django 6.0 on 2026-01-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_supplier_delivery_supplier_delivery_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=128)),
                ('trade_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('packaging', models.CharField(blank=True, max_length=64, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('last_updated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prices_in_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
