# Generated by Django 6.0.1 on 2026-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_productpricecomparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_island', models.CharField(max_length=64)),
                ('supermarket', models.CharField(max_length=128)),
                ('website', models.URLField(max_length=256)),
                ('platform', models.CharField(max_length=64)),
                ('scrapable', models.CharField(max_length=32)),
                ('product_selector', models.CharField(max_length=128)),
                ('title_selector', models.CharField(max_length=128)),
                ('price_selector', models.CharField(max_length=128)),
                ('js_render', models.CharField(max_length=16)),
                ('scrape_method', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
